export const Uebungen = {
  Brust: [
    { label: "Bankdrücken", value: "bankdrücken" },
    { label: "Schrägbankdrücken (positiv)", value: "schrägbankdrückenPos" },
    { label: "Schrägbankdrücken (negativ)", value: "schrägbankdrückenNeg" },
    { label: "Butterfly", value: "butterfly" },
    { label: "Cable Crossover", value: "cablecrossover" },
    { label: "Dips", value: "dips" },
    { label: "Liegestütze", value: "liegestütze" },
    { label: "Überzüge", value: "überzüge" },
  ],
  Schulter: [
    { label: "Schulterdrücken", value: "schulterdrücken" },
    { label: "Seitheben", value: "seitheben" },
    { label: "Frontheben", value: "frontheben" },
    { label: "Facepulls", value: "facepulls" },
    { label: "Reverse Butterfly", value: "reverseButterfly" },
  ],
  Rücken: [
    { label: "Latzug", value: "latzug" },
    { label: "Klimmzüge", value: "klimmzüge" },
    { label: "Überzüge", value: "überzüge" },
    { label: "Rudern", value: "rudern" },
    { label: "Kreuzheben", value: "kreuzheben" },
    { label: "Rückenstrecker", value: "rückenstrecker" },
  ],
  Beine: [
    { label: "Squats", value: "squats" },
    { label: "Kreuzheben", value: "kreuzheben" },
    { label: "Beinpresse", value: "beinpresse" },
    { label: "Beinstrecker", value: "beinstrecker" },
    { label: "Beinbeuger", value: "beinbeuger" },
    { label: "Abduktoren", value: "abduktoren" },
    { label: "Adduktoren", value: "adduktoren" },
    { label: "Rückenstrecker", value: "rückenstrecker" },
  ],
  Bizeps: [
    { label: "Langhantelcurls", value: "langhantelcurls" },
    { label: "Kurzhantelcurls", value: "kurzhantelcurls" },
    { label: "Hammercurls", value: "hammercurls" },
    { label: "Kabelcurls", value: "kabelcurls" },
  ],
  Trizeps: [
    { label: "Trizepsdrücken", value: "trizepsdrücken" },
    { label: "Frenchpress", value: "frenchpress" },
  ],
  Bauch: [
    { label: "SitUps", value: "situps" },
    { label: "Crunches", value: "crunches" },
    { label: "Beinheben", value: "beinheben" },
    { label: "planks", value: "planks" },
  ],
  Nacken: [
    { label: "Nackenheben", value: "nackenheben" },
    { label: "Kreuzheben", value: "kreuzheben" },
  ],
};
